Store.create(name: "Royal Furniture", address: "5365 N Blackstone Ave, Fresno, CA 93710", phone: "(559) 431-1217", hours: "Monday	10AM–8PM, Tuesday	10AM–8PM, Wednesday	10AM–8PM, Thursday	10AM–8PM, Friday	10AM–8PM, Saturday	10AM–8PM, Sunday	10:30AM–8PM", store_copy: "Occupy kitsch plaid cornhole tattooed sartorial four dollar toast pour-over. Irony tilde retro, messenger bag hammock gluten-free seitan +1 intelligentsia literally. Chicharrones ramps forage, vegan tousled wayfarers franzen.", store_image: "https://s3-us-west-1.amazonaws.com/royal-furniture/IMG_0157.JPG", gmaps: "https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d12776.556342946536!2d-119.7919216!3d36.8151869!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x3ebee9e8532f014a!2sRoyal+Furniture!5e0!3m2!1sen!2sus!4v1506130453305")

coaster = Brand.new(name: "Coaster", video: nil, logo: "https://s3-us-west-2.amazonaws.com/fdn-images-2/img/dealer/40370/Upload/logo/e973633264e44b1c9a742125cb9d13bb.jpg", category: "furniture")
coaster.save!

homelegance = Brand.new(name: "Homelegance", video: nil, logo: "https://www.homelegance.com/wp-content/themes/h2/images/logo.png", category: "furniture")
homelegance.save!

acme = Brand.new(name: "Acme", logo: "https://www.acmecorp.com/skin/frontend/acmefurniture/acme/images/acme_logo.png", category: "furniture")
acme.save!

foa = Brand.new(name: "Furniture of America", logo: "https://scontent.fsnc1-1.fna.fbcdn.net/v/t1.0-9/1454611_875423402508474_6570122812190848548_n.jpg?oh=d545c7ffb3dfccb89eae34700165a300&oe=5A215584", category: "furniture")
foa.save!

urban = Brand.new(name: "Urban Styles", logo: "http://www.urbanstyles.net/skin/frontend/default/theme638/images/logo.png", category: "furniture")
urban.save!

new_classic = Brand.new(name: "New Classic", logo: "http://newclassicfurniture.com/wp-content/uploads/2016/09/logo-new-1.jpg", category: "furniture")
new_classic.save!

gomen = Brand.new(name: "Gomen Furniture", logo: "http://static1.squarespace.com/static/53152d7fe4b05e4b3991347b/t/5318c064e4b02cc79a151e66/1462490666933/?format=500w", category: "furniture")
gomen.save!

stanford = Brand.new(name: "Stanford Furniture", category: "furniture")
stanford.save!

diamond = Brand.new(name: "Diamond Mattress", category: "mattresses", logo: "")
diamond.save!

Product.create(name:"Doyle Traditional Oval End Table with Glass Inlay Top" , image: "http://imageresizer.furnituredealer.net/img/remote/s3-us-west-2.amazonaws.com/fdn-images-2/img/products%2Fcoaster%2Fcolor%2Fdoyle_3891-b.jpg?width=500&height=500", description: "Traditional occasional tables feature hand carved detailing with glass inlay. All pieces feature storage shelves. Ornate legs carved into a serpentine shape", category: "occasional", style: "traditional", brand_id: coaster.id)

Product.create(name:"Doyle Traditional Oval Cocktail Table with Glass Inlay Top" , image: "http://imageresizer.furnituredealer.net/img/remote/s3-us-west-2.amazonaws.com/fdn-images-2/img/products%2Fcoaster%2Fcolor%2Fdoyle_3892-b.jpg?width=500&height=500", description: "Traditional occasional tables feature hand carved detailing with glass inlay. All pieces feature storage shelves. Ornate legs carved into a serpentine shape", category: "occasional", style: "traditional", brand_id: coaster.id)

Product.create(name:"Doyle Traditional Sofa Table with Glass Inlay Top" , image: "http://imageresizer.furnituredealer.net/img/remote/s3-us-west-2.amazonaws.com/fdn-images-2/img/products%2Fcoaster%2Fcolor%2Fdoyle_3893-b.jpg?width=500&height=500", description: "Traditional occasional tables feature hand carved detailing with glass inlay. All pieces feature storage shelves. Ornate legs carved into a serpentine shape", category: "occasional", style: "traditional", brand_id: coaster.id)

Product.create(name:"Entertainment Units 60\" TV Stand with Shelves" , image: "http://imageresizer.furnituredealer.net/img/remote/s3-us-west-2.amazonaws.com/fdn-images-2/img/products%2Fcoaster%2Fcolor%2Fwall%20units_700681-b2.jpg?width=500&height=500", description: "Features large-scale center console with plenty of storage. Constructed with metal and tempered glass", category: "occasional", style: "contemporary", brand_id: coaster.id)

Product.create(name:"Schleiger Collection" , image: "https://www.homelegance.com/wp-content/uploads/2017/03/5400-1__1-750x500.jpg", description: "Transitionally styled with a burnished brown finish, the Schleiger Collection features bold accenting that lends to a rustic industrial interpretation. Substantial framing provides a masculine profile while decorative metal and rivet banding on each piece of the group furthers the look. Each case piece features metal horizontal hardware.", category: "bedroom", style: "rustic", brand_id: homelegance.id, pieces: 4)

Product.create(name:"Porter Bedroom Set" , image: "https://www.homelegance.com/wp-content/uploads/2015/02/1852-1__11-750x500.jpg", description: "With an intricate design lending to the modern look of the Porter Collection, your bedroom will reflect your taste for sophisticated contemporary living. A warm walnut finish and the look of woven detailing highlight the natural wood grain of the veneer on each piece of the collection. Knob hardware blends effortlessly to create an unobtrusive accent to the case goods. The bed features framing on the headboard and low-profile footboard that subtly incorporates the prominent woven design.", category: "bedroom", style: "contemporary", brand_id: homelegance.id, pieces: 4)

Product.create(name:"Lavonia Bedroom Set" , image: "https://www.homelegance.com/wp-content/uploads/2017/03/1707-1__11-750x500.jpg", description: "Transitional styling is paired with classic appointments and modern technology to create the Lavonia Collection. The eye-catching dramatic curve of the headboard creates instant appeal when taking in the design of this collection. The framing of the headboard carries over to the design of the low profile footboard and turned-foot supported recessed drawer front case pieces. Modern technology comes into play with the power strip – with USB port – charging station that is mounted to the upper back of the nightstand. A gray wire-brushed finish over oak veneers furthers the classic look of this bedroom collection", category: "bedroom", style: "rustic", brand_id: homelegance.id, pieces: 4)

Product.create(name:"Erwan Bedroom Set" , image: "https://www.homelegance.com/wp-content/uploads/2017/03/1961-1__1-750x500.jpg", description: "Taking a nod from contemporary design, the look of the Erwan Collection is a versatile choice for the modern home. A rich espresso finish highlights the okume veneer and beveled drawer fronts which are punctuated with gunmetal finished hardware and bold framing that blend together to create this soft contemporary bedroom offering", category: "bedroom", style: "contemporary", brand_id: homelegance.id, pieces: 4)

Product.create(name:"Schleiger Dining Set" , image: "https://www.homelegance.com/wp-content/uploads/2016/02/5400-94__11-750x500.jpg", description: "Transitionally styled with a burnished brown finish, the Schleiger Collection features bold accenting and functional storage options. Sturdy legs support the metal and rivet banded table top with chair and bench options, allowing for versatile seating configurations. Metal and rivet banding with nailhead accent also features prominently on the open hutch and buffet, and mobile kitchen cart.", category: "dining", style: "rustic", brand_id: homelegance.id, counter_height: false)

Product.create(name:"Crown Point Dining Set" , image: "https://www.homelegance.com/wp-content/uploads/2011/10/1372-78_1-750x500.jpg", description: "Adorn your dining area with Crown Point Collection. This grand scale casual dining in warm merlot finish is as strong and durable as they are stunning. Table top is constructed of mango veneer with strong support tapered legs. Attractive X-back dining chair with comfortable leather-look dark brown seat completes the unsophisticated streamlined look", category: "dining", style: "contemporary", brand_id: homelegance.id, counter_height: false)

Product.create(name:"Crown Point Dining Set" , image: "https://www.homelegance.com/wp-content/uploads/2011/10/1372-36_1-750x500.jpg", description: "Adorn your dining area with Crown Point Collection. This grand scale casual dining in warm merlot finish is as strong and durable as they are stunning. Table top is constructed of mango veneer with strong support tapered legs. Attractive X-back dining chair with comfortable leather-look dark brown seat completes the unsophisticated streamlined look", category: "dining", style: "contemporary", brand_id: homelegance.id, counter_height: true)

Product.create(name:"Compson Dinging Set" , image: "https://www.homelegance.com/wp-content/uploads/2016/02/5431-77__11-750x500.jpg", description: "With lines that lean to contemporary and a natural finish that can be placed in transitional settings, the unique design of the Compson Collection allows for your decorative imagination to run wild. Convenience factors of the self-storing table leaf, and the two tone finish that highlights the natural grain of the walnut veneer table top, are some of the valuable features offered in this offering. Wood framed chairs have chocolate brown fabric seats and backs that further the two-tone look of the collection. Following the curve of the table top is the optional 60-inch bench. The accompanying server features an open display shelf along with drawer and door storage for stowing your tabletop accessories.", category: "dining", style: "contemporary", brand_id: homelegance.id, counter_height: false)

Product.create(name:"Allegra Bedroom Set" , image: "http://newclassicfurniture.com/wp-content/uploads/2016/06/00-2159_H1.jpg", description: "From our Royal Classics Division comes Allegra, a sophisticated suite with raised panels, bun feet, storage galore and finished in a silky Pewter color.", category: "bedroom", style: "traditional", brand_id: new_classic.id, pieces: 5)

Product.create(name:"Hailey Bedroom Set" , image: "http://newclassicfurniture.com/wp-content/uploads/2016/06/hailey_panelbed_hr.jpg", description: "The Hailey collection offers the rustic charm of country living with sturdy ash solids and a toffee finish. Bonnet top crown accents the headboard style panels in the bed, while hefty turn post caps add substance. Full return trims, scalloped aprons, and antiqued bronze hardware further characterize the homespun Hailey.", category: "bedroom", style: "rustic", brand_id: new_classic.id, pieces: 5)

Product.create(name:"Jaquelyn Bedroom Set" , image: "http://newclassicfurniture.com/wp-content/uploads/2016/07/b8651-5304.jpg", description: "Sweeping carvings and gorgeous veneer work highlight the Jaquelyn collection. Available in Cherry or Black finishes, the Jaquelyn evokes a French traditional styling in a compact size. Available in youth and master bedroom sizes.", category: "bedroom", style: "traditional", brand_id: new_classic.id, pieces: 5)

Product.create(name:"Valentino Bedroom Set" , image: "http://newclassicfurniture.com/wp-content/uploads/2016/07/00-9698_H1.jpg", description: "Framing each piece is a decorative beveled mirror accent that enhances the illumination from the touch-engaged LED back-light of the headboard and mirror. Alligator embossing and high polished crystal-enhanced hardware boldly accent the silver finish of the collection.", category: "bedroom", style: "contemporary", brand_id: new_classic.id, pieces: 5)

Product.create(name:"Sheridan Bedroom Set" , image: "http://newclassicfurniture.com/wp-content/uploads/2016/07/sheridan_hr_rgb_jpg.jpg", description: "The Sheridan collection offers a luxurious ambience with exquisite detail and refined style. Distinctive style elements include bookmatched veneers framed with contrasting edge banding, inlaid detailing on case tops, reeded pilasters, and antique brass finished hardware, Combining tradition with modern day convenience, Sheridan offers optional underbed storage and felt lined top drawers in the dresser, chest, and nightstand.", category: "bedroom", style: "traditional", brand_id: new_classic.id, pieces: 5)

Product.create(name:"Sheridan Dining Set" , image: "http://newclassicfurniture.com/wp-content/uploads/2016/07/nc_sheridan_rect_dininghr-2.jpg", description: "The Sheridan collection boasts old world charm and modern luxury with bookmatched veneer tabletops, reeded table leg, and shaped apron detail anchored by a unique hexagonal foot. Crafted of hardwood solids and veneers and finished in rich burnished cherry. Options include round or rectangle dining table.", category: "dining", style: "traditional", brand_id: new_classic.id, counter_height: false)

Product.create(name:"Sheridan Occasional Set" , image: "http://newclassicfurniture.com/wp-content/uploads/2016/07/sheridan.jpg", description: "The classically beautiful Sheridan collection stands out with bookmatched veneer panels topped off with a glimmering burnished cherry finish. Cocktail table’s lift top lid and drawers hide additional storage. Complete the look with one of our matching media furniture consoles.", category: "occasional", style: "traditional", brand_id: new_classic.id)

Product.create(name:"Bixby Dining Set" , image: "http://newclassicfurniture.com/wp-content/uploads/2016/07/bixby-oval-dining-hr.jpg", description: "The Bixby Dining room evokes a traditional feel with nail head trim seat cushions, shaped legs and wheat back chair. A rich espresso finish updates the look while functional under table shelving is attractive and handy.", category: "dining", style: "traditional", brand_id: new_classic.id, counter_height: false)

Product.create(name:"Bixby Dining Set" , image: "http://newclassicfurniture.com/wp-content/uploads/2016/07/bixby-counter-table-hr.jpg", description: "The Bixby Dining room evokes a traditional feel with nail head trim seat cushions, shaped legs and wheat back chair. A rich espresso finish updates the look while functional under table shelving is attractive and handy.", category: "dining", style: "traditional", brand_id: new_classic.id, counter_height: true)

Product.create(name:"Gillian Dining Set" , image: "http://newclassicfurniture.com/wp-content/uploads/2016/11/galian-001.jpg", description: "The Gillian Dining’s mid century modern influence is enhanced with chair back treatments. Two tone stain highlights the unique grain patterns of the wood. Dining Table includes 18″ Leaf.", category: "dining", style: "contemporary", brand_id: new_classic.id, counter_height: false)

Product.create(name:"Gillian Dining Set" , image: "http://newclassicfurniture.com/wp-content/uploads/2016/11/galian-002.jpg", description: "The Gillian Dining’s mid century modern influence is enhanced with chair back treatments. Two tone stain highlights the unique grain patterns of the wood. Dining Table includes 18″ Leaf.", category: "dining", style: "contemporary", brand_id: new_classic.id, counter_height: true)

Product.create(name:"Versailles Bedroom Set" , image: "https://www.acmecorp.com/media//catalog/category/cache/801x571/21130Q_SET_L_3.jpg", description: "The Versailles collection harmonizes traditional details with functional design to accommodate today’s styles. This bedroom collection features bone white veneers, nailhead trim accents, button tufted headboard/ footboard , padded side rails, and hand-carved style wood drawer overlays throughout all case pieces. The ample storage case pieces, beveled mirror, felt lined drawers, and antique finish hardware make this set truly elegant and will be a great addition to your home.", category: "bedroom", style: "traditional", brand_id: coaster.id, pieces: 5)

Product.create(name:"Versailles Bedroom Set" , image: "https://www.acmecorp.com/media//catalog/category/cache/801x571/21120Q_SET_L_1.jpg", description: "Sleep like royalty with this Versailles Bed Set. The bedroom set was inspired by old European design. The bed features carved scrollwork accent with nailhead trim décor and tufted upholstery on both headboard and footboard. The accent pieces crafted in wood with cherry oak veneer finish, and also include regal features such as ample storage, beveled mirror, felt lined drawers, and brown copper finish hardware. The carved details and cherry oak finish give a royal look to your bedroom space with this bed.", category: "bedroom", style: "traditional", brand_id: coaster.id, pieces: 5)

Product.create(name:"Faye Bed" , image: "https://www.acmecorp.com/media//catalog/category/cache/801x571/20650Q_SET_L_1.jpg", description: "The Faye collection offers different bed options. The bed combines the traditional elements with the modern design. It features button tufted headboard with linen fabric. The wingback headboard design with the espresso tapered leg creates the luxurious atmosphere to fit every decoration.", category: "bedroom", style: "contemporary", brand_id: coaster.id, pieces: 1)

Product.create(name:"Versailles Dining Set" , image: "https://www.acmecorp.com/media//catalog/category/cache/801x571/61130_SET_L_1.jpg", description: "Irresistibly inviting, the Versailles collection displays the unrivaled beauty of the traditional dining. The dining table reflects highly decorative base with oversized scrolled feet, and the upholstered and tapestried chairs with the deep button tufted and nail head trim accents add classic character and represents luxurious detailing. This collection offers three styles of tables and two finishes for you to choose, and it would be perfect for any formal dining room.", category: "dining", style: "traditional", brand_id: coaster.id, counter_height: false)

Product.create(name:"Versailles Dining Set" , image: "https://www.acmecorp.com/media//catalog/category/cache/801x571/61100_SET_L_1.jpg", description: "Irresistibly inviting, the Versailles collection displays the unrivaled beauty of the traditional dining. The dining table reflects highly decorative base with oversized scrolled feet, and the upholstered and tapestried chairs with the deep button tufted and nail head trim accents add classic character and represents luxurious detailing. This collection offers three styles of tables and two finishes for you to choose, and it would be perfect for any formal dining room.", category: "dining", style: "traditional", brand_id: coaster.id, counter_height: false)

Product.create(name:"Lexis Bunk Bed" , image: "https://www.foagroup.com/media/catalog/product/cache/1/image/040ec09b1e35df139433887a97daa66f/c/m/cm-bk1036bw.jpg", description: "Strikingly unique, this bunk bed is as beautiful as it is functional. The upper bed has safety rails, and the horizontal bars in between two curved metal posts also act as an access ladder to the top bunk.", category: "bedroom", style: "contemporary", brand_id: foa.id, pieces: 1)

Product.create(name:"Woodridge Bunk Bed" , image: "https://www.foagroup.com/media/catalog/product/cache/1/image/040ec09b1e35df139433887a97daa66f/i/m/image_184.jpg", description: "Built-in steps and drawers make this bunk bed a perfect upgrade to your child", category: "bedroom", style: "contemporary", brand_id: foa.id, pieces: 1)

Product.create(name:"Solpine Bunk Bed" , image: "https://www.foagroup.com/media/catalog/product/cache/1/image/040ec09b1e35df139433887a97daa66f/c/m/cm-bk618t-gy.jpg", description: "A unique curved wooden post, along with its curved attached ladder, gives this bunk bed an exotic look. The posts are thick and sturdy, which underscores its bold and solid structure.", category: "bedroom", style: "contemporary", brand_id: foa.id, pieces: 1)

Product.create(name:"Gartel Day Bed" , image: "https://www.foagroup.com/media/catalog/product/cache/1/image/040ec09b1e35df139433887a97daa66f/c/m/cm1610.jpg", description: "Throw the ultimate slumber party with this espresso finished 3-layer nesting daybed! Have friends or family comfortably tucked in any of the three twin-size sleeping spaces. When it comes time for them to leave, roll the frames back under the daybed and regain valuable floor space. The slatted ends and plank style sides give a charming visual, adding a touch of style to a piece with tons of function.", category: "bedroom", style: "contemporary", brand_id: foa.id, pieces: 1)

Product.create(name:"Sania Dining Set" , image: "https://www.foagroup.com/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/c/m/cm3324bk-t.jpg", description: "Rustic charm meets upscale design in the form of this stunning collection. The rustic wood grain and antique black finish take you to a charming farmhouse somewhere in the countryside, achieving an inviting, homey atmosphere that will have family and friends coming back for more. Elegant ivory linen-like chairs add sophisticated appeal with their wingback sides, button tufting and nailhead trim", category: "dining", style: "traditional", brand_id: foa.id, counter_height: false)

Product.create(name:"Richfield Dining Set" , image: "https://www.foagroup.com/media/catalog/product/cache/1/image/040ec09b1e35df139433887a97daa66f/c/m/cm3362t.jpg", description: "Quite the attention grabber, this collection will immediately become the focal point of your home. Family and friends are sure to admire your fine taste when they lay eyes on this one-of-a-kind table. Bold posts create a sturdy base for the 12mm tempered glass top featuring smooth, curved edges. Matching padded faux leather chairs complete the look with their U-shaped chrome legs, which comes in either white or black. This set is available in both standard and counter height", category: "dining", style: "contemporary", brand_id: foa.id, counter_height: false)

Product.create(name:"Lettie Pushback Chair" , image: "https://www.foagroup.com/media/catalog/product/cache/1/image/040ec09b1e35df139433887a97daa66f/c/m/cm-rc6457.jpg", description: "Get the look of an elegant accent chair with the comfort of a recliner! Upholstered in fl annelette fabric, this stunning beige push-back chair features espresso legs, stylish rolled arms and attractive welting trim to dress up a formal living room or play down a fun and casual space", category: "seating", style: "contemporary", brand_id: foa.id, sofa_love: false)

Product.create(name:"Farmhouse Dining Set" , image: "http://www.urbanstyles.net/media/catalog/product/cache/1/image/900x600/9df78eab33525d08d6e5fb8d27136e95/f/a/farmhouse_set.jpg", description: "Rustic and simple this set will make any dining room feel complete. With solid design and your choice of bench or chairs every meal will feel like a get away into the countryside.", category: "dining", style: "rustic", brand_id: urban.id, counter_height: false)

Product.create(name:"Liberty Dining Set" , image: "http://www.urbanstyles.net/media/catalog/product/cache/1/image/800x800/9df78eab33525d08d6e5fb8d27136e95/l/i/liberty_main.jpg", description: "Distinguish your dining room with this dark toned dining set. Dark oak finishes feature rustic tones that add rich character to the clean designs. Comforting leatherette tightly wraps the cushioned chairs and slat backs provide a breathable back rest. Welcome this dining set for sophistication and unparalleled refinment.", category: "dining", style: "contemporary", brand_id: urban.id, counter_height: false)

Product.create(name:"Palmdale Dining Set" , image: "http://www.urbanstyles.net/media/catalog/product/cache/1/image/900x600/9df78eab33525d08d6e5fb8d27136e95/p/a/palmdale_dining.jpg", description: "Entertain your guest with this French country design dining set. Table features a butterfly leaf, and chairs are upholstered in rustic faux leather.", category: "dining", style: "contemporary", brand_id: urban.id, counter_height: false)

Product.create(name: "Melanie Sectional", image: "http://gomenfurniture.mov.mn/files/sanpham/58/1/jpg/melanie.jpg", description: "", category: "seating", style: "contemporary", brand_id: gomen.id, sofa_love: false)

Product.create(name: "Nicole Sofa Set", image: "http://gomenfurniture.mov.mn/files/sanpham/26/1/jpg/nicole.jpg", description: "", category: "seating", style: "contemporary", brand_id: gomen.id, sofa_love: true)

Product.create(name: "Sunrise Sofa Set", image: "http://gomenfurniture.mov.mn/files/sanpham/22/1/jpg/sunrise.jpg", description: "", category: "seating", style: "rustic", brand_id: gomen.id, sofa_love: true)

Product.create(name: "Polo Sofa Set", image: "http://gomenfurniture.mov.mn/files/sanpham/48/1/jpg/polo.jpg", description: "", category: "seating", style: "contemporary", brand_id: gomen.id, sofa_love: true)

Product.create(name: "Dallas Sofa Set", image: "http://danstoller.mov.mn/files/sanpham/37/1/jpg/dallas.jpg", description: "", category: "seating", style: "contemporary", brand_id: stanford.id, sofa_love: true)

Product.create(name: "Oxford Sectional", image: "http://danstoller.mov.mn/files/sanpham/16/1/jpg/oxford.jpg", description: "", category: "seating", style: "contemporary", brand_id: stanford.id, sofa_love: false)

Product.create(name: "Roxanne Sofa Set", image: "http://danstoller.mov.mn/files/sanpham/5/1/jpg/roxanne-gray.jpg", description: "", category: "seating", style: "contemporary", brand_id: stanford.id, sofa_love: true)

Mattress.create(name: "Holiday Medium", brand_id: diamond.id, price: 749, sizes: ["Twin", "Full", "Queen", "King"], description: "The Dream Collection combines our 744 foam-encased, individually-wrapped coil support system and visco memory foam to help you fall asleep faster, stay asleep longer and wake up feeling refreshed. Dream Collection beds do not transfer motion between partners, allowing you to sleep throughout the night and receive deeper, more rejuvenating rest. These beds also reduce tossing and turning through the pressure-relieving support of our luxurious Eco-Flex plant-based comfort layers.", firmness: "medium", warranty_length: 20, components: ["gel", "pocketed_coil"], adjustable: true, image: "http://www.diamondmattress.com/Resources/ProductPhotos/Holiday%20ET_3.jpg", price_sizes: {"twin": {"matt": 399, "set": 499}, "full": {"matt": 499, "set": 599}, "queen": {"matt": 599, "set": 749}, "king": {"matt":849, "set": 1049}})

Mattress.create(name: "Holiday Firm", brand_id: diamond.id, price: 749, sizes: ["Twin", "Full", "Queen", "King"], description: "The Dream Collection combines our 744 foam-encased, individually-wrapped coil support system and visco memory foam to help you fall asleep faster, stay asleep longer and wake up feeling refreshed. Dream Collection beds do not transfer motion between partners, allowing you to sleep throughout the night and receive deeper, more rejuvenating rest. These beds also reduce tossing and turning through the pressure-relieving support of our luxurious Eco-Flex plant-based comfort layers.", firmness: "firm", warranty_length: 20, components: ["gel", "pocketed_coil"], adjustable: true, image: "http://www.diamondmattress.com/Resources/ProductPhotos/Holiday%20ET_3.jpg", price_sizes: {"twin": {"matt": 399, "set": 499}, "full": {"matt": 499, "set": 599}, "queen": {"matt": 599, "set": 749}, "king": {"matt":849, "set": 1049}})

Mattress.create(name: "Holiday Pillow Top", brand_id: diamond.id, price: 849, sizes: ["Twin", "Full", "Queen", "King"], description: "The Dream Collection combines our 744 foam-encased, individually-wrapped coil support system and visco memory foam to help you fall asleep faster, stay asleep longer and wake up feeling refreshed. Dream Collection beds do not transfer motion between partners, allowing you to sleep throughout the night and receive deeper, more rejuvenating rest. These beds also reduce tossing and turning through the pressure-relieving support of our luxurious Eco-Flex plant-based comfort layers.", firmness: "plush", warranty_length: 20, components: ["gel", "pocketed_coil"], adjustable: true, image: "http://www.diamondmattress.com/Resources/ProductPhotos/Holiday%20ET_3.jpg", price_sizes: {"twin": {"matt": 499, "set": 599}, "full": {"matt": 599, "set": 749}, "queen": {"matt": 699, "set": 849}, "king": {"matt":949, "set": 1199}})

Mattress.create(name: "Holiday Euro Top", brand_id: diamond.id, price: 799, sizes: ["Twin", "Full", "Queen", "King"], description: "The Dream Collection combines our 744 foam-encased, individually-wrapped coil support system and visco memory foam to help you fall asleep faster, stay asleep longer and wake up feeling refreshed. Dream Collection beds do not transfer motion between partners, allowing you to sleep throughout the night and receive deeper, more rejuvenating rest. These beds also reduce tossing and turning through the pressure-relieving support of our luxurious Eco-Flex plant-based comfort layers.", firmness: "plush", warranty_length: 20, components: ["gel", "pocketed_coil"], adjustable: true, image: "http://www.diamondmattress.com/Resources/ProductPhotos/Holiday%20ET_3.jpg", price_sizes: {"twin": {"matt": 449, "set": 549}, "full": {"matt": 549, "set": 649}, "queen": {"matt": 649, "set": 799}, "king": {"matt":899, "set": 1099}})

Mattress.create(name: "Shadow Luxury Medium", brand_id: diamond.id, price: 1099, sizes: ["Twin", "Full", "Queen", "King"], description: "The Collection is designed for a luxurious, comfortable and extravagant night's sleep. It's technically developed to help you fall asleep faster, stay asleep longer and wake up feeling refreshed, The Black Diamond beds do not transfer motion between partners, allowing you to sleep throughout the night and receive deeper, more rejuvenating rest. These beds also reduce tossing and turning through the pressure relieving support of our luxurious Eco-Flex plant-based comfort layers and the most advanced, high quality components.", firmness: "medium", warranty_length: 20, components: ["gel_foam", "pocketed_coil"], adjustable: true, image: "http://www.diamondmattress.com/Resources/ProductPhotos/A%20BD_Grandeur_Scaled.jpg", price_sizes: {"twin": {"matt": 599, "set": 699}, "full": {"matt": 799, "set": 899}, "queen": {"matt": 999, "set": 1099}, "king": {"matt":1199, "set": 1399}})

Mattress.create(name: "Highlight Medium", brand_id: diamond.id, price: 1099, sizes: ["Twin", "Full", "Queen", "King"], description: "The CoolTouchGEL Memory Foam Collection has been designed using our advanced Gel technology that uses chilling beads to maintain balanced body temperature. Combining the benefits of our ventilated and open-cell design, CoolTouchGEL Memory Foam is 12x more breathable than any other nationally advertised memory foam product.", firmness: "medium", warranty_length: 20, components: ["gel_foam", "memory_foam"], adjustable: true, image: "http://www.diamondmattress.com/Resources/ProductPhotos/CT_Enchantment%20Med.jpg", price_sizes: {"twin": {"matt": 499, "set": 599}, "full": {"matt": 599, "set": 749}, "queen": {"matt": 699, "set": 849}, "king": {"matt":949, "set": 1199}})
